# Permalinks
permalink:           pretty

# Setup
title:               newPage  
tagline:             John Letourneux
url:                 http://github.com/john-letourneux
paginate:            1
baseurl:             ""
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John Letourneux
  url:               
  email:             john.letourneux@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
